export default{
    // url : 'https://www.xytzq.cn:9443/tzq/',
    // studentUrl:'https://www.xytzq.cn/student/index/index.html#home?',
    // adminUrl:'https://www.xytzq.cn/orgmanage/index.html',
    // scoreUrl:'https://www.xytzq.cn/pcproject.html#/home',
    // currenturl : 'https://www.xytzq.cn',
    // webSockentUrl:'wss://www.xytzq.cn:9443/tzq/webSocketServer',
    // projectRoomUrl:'https://www.xytzq.cn/student/projectroom/index-tzr.html',
    // viewUrl:'https://www.xytzq.cn/orgmanage',  //预览的地址

    url : 'https://www.xytzq.cn:9443/tzq/',
    // url: 'http://192.168.1.195:8080/tzq/',
    studentUrl:'https://www.xytzq.cn/student/index/index.html#home?',
    studentUrlGo:'https://www.xytzq.cn/student/index/index.html#home',
    adminUrl:'https://www.xytzq.cn/orgmanage/index.html',
    scoreUrl:'http://192.168.1.124/pcproject.html#/home',
    currenturl : 'https://www.xytzq.cn',
    webSockentUrl:'ws://192.168.1.194:8080/tzq/webSocketServer',
    projectRoomUrl:'https://www.xytzq.cn/student/projectroom/index-tzr.html',
    personrequirementUrl:'http://192.168.1.194/student/index/index.html#demand_under?',
    viewUrl:'https://www.xytzq.cn/orgmanage',  //预览的地址

    checked:'',
    nochecked:'',
    PauseChecked:'',
    yearvalue:'',
    statevalue:'',
    organizavalue:'',
    accountname:'',
    aftersure:'',
    getorgData:'',
    getcityData:'',
    getStageData:'',
    getTradeData:'',
    indextosapienstradid:'',
    indextosapienstradname:'',
    indextohotprojectstageid:'',
    indextohotprojectstagename:'',
}
