export default{
    // url: 'http://test.xytzq.cn:9443/tzq/',
    // studentUrl:'http://test.xytzq.cn/student/index/index.html#home?',
    // adminUrl:'http://test.xytzq.cn/orgmanage/index.html',
    // scoreUrl:'http://test.xytzq.cn/pcproject.html#/home',
    // currenturl: 'http://test.xytzq.cn',
    // webSockentUrl:'wss://test.xytzq.cn:9443/tzq/webSocketServer',
    // projectRoomUrl:'http://test.xytzq.cn/student/projectroom/index-tzr.html',
    // viewUrl:'http://test.xytzq.cn/orgmanage',  //预览的地址

    url: 'http://test.xytzq.cn:9199/tzq/',
    studentUrl:'http://test.xytzq.cn/student/index/index.html#home?',
    studentUrlGo:'http://test.xytzq.cn/student/index/index.html#home',
    adminUrl:'http://test.xytzq.cn/orgmanage/index.html',
    scoreUrl:'http://192.168.1.120/pcproject.html#/teaching',
    currenturl: 'http://192.168.1.120/',
    webSockentUrl:'wss://www.xytzq.cn:9443/tzq/webSocketServer',
    projectRoomUrl:'http://test.xytzq.cn/student/projectroom/index-tzr.html',
    personrequirementUrl:'http://test.xytzq.cn/student/index/index.html#demand_under?',
    viewUrl:'http://test.xytzq.cn/orgmanage',  //预览的地址

    checked:'',
    nochecked:'',
    PauseChecked:'',
    yearvalue:'',
    statevalue:'',
    organizavalue:'',
    accountname:'',
    aftersure:'',
    getorgData:'',
    getcityData:'',
    getStageData:'',
    getTradeData:'',
    indextosapienstradid:'',
    indextosapienstradname:'',
    indextohotprojectstageid:'',
    indextohotprojectstagename:'',
    pcprojectTeachingHeight:'',
}
